import type { NextPage } from 'next';
import Head from 'next/head';
import { Box, Flex, VStack } from '@chakra-ui/react';
import {
  HiOutlineUserGroup,
  HiOutlineChat,
  HiOutlineCog,
  HiOutlineLogout,
} from 'react-icons/hi';
import { useWallet } from 'use-wallet';
import { RiLandscapeLine } from 'react-icons/ri';

import { useGun } from '@/contexts/gun';
import ChatContainer from '@/components/ChatContainer';

const commonIconProps = {
  //gray.400
  size: 25,
  cursor: 'pointer',
};

const commonBoxIconProps = {
  color: 'gray.400',
  _hover: {
    color: 'blue.500',
  },
};

const Home: NextPage = () => {
  const { SEA } = useGun();

  const secretWord = 'secret';
  const pair = async () => {
    try {
      const msg = await SEA.encrypt('Ricky yen!', secretWord);
      console.log(msg, await SEA.decrypt(msg, secretWord));
    } catch (err) {
      console.log(err);
    }
  };

  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex w="full" h="100vh">
        <VStack flexDirection="column" px={2} py={2} boxSizing="border-box">
          <Box bg="blue.500" p={2} mt={5}>
            <RiLandscapeLine color="white" size={25} />
          </Box>
          <VStack justifyContent="space-between" h="full" py={6}>
            <VStack spacing={8} onClick={pair}>
              <Box {...commonBoxIconProps}>
                <HiOutlineChat {...commonIconProps} />
              </Box>
              <Box {...commonBoxIconProps}>
                <HiOutlineUserGroup {...commonIconProps} />
              </Box>
              <Box {...commonBoxIconProps}>
                <HiOutlineCog {...commonIconProps} />
              </Box>
            </VStack>
            <Box {...commonBoxIconProps}>
              <HiOutlineLogout {...commonIconProps} />
            </Box>
          </VStack>
        </VStack>
        <ChatContainer />
      </Flex>
    </Box>
  );
};

export default Home;
